### ISSUE TITLE
Does localization file have to be a .js file rather than .json file if included after library?

### ISSUE THREAD

**Issue by cyphix333** [eligrey/l10n.js#37]
I noticed in the Usage instructions you stated to:

Place `<script type="text/javascript" src="path/to/l10n.js"></script>` anywhere after the `<link>` tag.

I presume the `link` tags is referencing the localization `.json` file?

However I noticed in the **demo** you stored your localization in a `.js` file and included it _after_ the library.

What is the difference?

**Comment by ranand16** [comment]
Did someone get the solution for this?

**Comment by eligrey** [comment]
`<link rel="localization">` needs to be JSON l10n.js data, whereas `<script>` elements must link to JavaScript files that call `String.toLocaleString(JSON l10n.js data here)`.

**Comment by ranand16** [comment]
This is the way how I did it
```
String.toLocaleString({
	"en":"json/en.json",
	"es":"json/spanish.json",
	"ja":"json/japaneese.json",
	"fr":"json/french.json",
	"pt":"json/portugeese.json"
});

```
